name: Pipeline

on: [push, pull_request]

jobs:
  build:
    name: "Lint and Deploy"
    runs-on: ubuntu-latest
    env:
      TERM: xterm-256color
      BATECT_CACHE_TYPE: directory
      BATECT_ENABLE_TELEMETRY: true
      DOCKER_BUILDKIT: 1

    steps:
      - uses: actions/checkout@v1

      - name: Cache batect
        uses: actions/cache@v1
        with:
          path: ~/.batect/cache
          key: batect-${{ hashFiles('batect') }}

      - name: Lint Terraform files
        run: ./batect lintTerraform

      - name: Check code files have license header
        run: ./batect checkLicenseHeader

      - name: Log in to GCP
        run: ./batect setupGCPServiceAccount
        if: github.repository == 'batect/updates.batect.dev' && github.ref == 'refs/heads/master' && github.event_name == 'push'
        env:
          GCP_SERVICE_ACCOUNT_EMAIL: github-actions@batect-updates-prod.iam.gserviceaccount.com
          GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Setup Cloudflare key
        run: ./batect setupCloudflareKey
        if: github.repository == 'batect/updates.batect.dev' && github.ref == 'refs/heads/master' && github.event_name == 'push'
        env:
          CLOUDFLARE_KEY: ${{ secrets.CLOUDFLARE_KEY }}

      - name: Setup Terraform
        run: ./batect setupTerraform
        if: github.repository == 'batect/updates.batect.dev' && github.ref == 'refs/heads/master' && github.event_name == 'push'

      - name: Apply Terraform
        run: ./batect applyTerraform
        if: github.repository == 'batect/updates.batect.dev' && github.ref == 'refs/heads/master' && github.event_name == 'push'

      - name: Cleanup credentials
        run: sudo rm -rf .creds .gcloud

      - name: Run smoke test
        run: ./batect smokeTest
        if: github.repository == 'batect/updates.batect.dev' && github.ref == 'refs/heads/master' && github.event_name == 'push'
